import pygame, os, random
pygame.init()
#kolory
SKYBLUE = pygame.color.THECOLORS['skyblue']
DARKRED = pygame.color.THECOLORS['darkred']
LIGHTRED = pygame.color.THECOLORS['palevioletred']
DARKGREEN = pygame.color.THECOLORS['darkgreen']
BLACK = pygame.color.THECOLORS['black']
LIGHTGREEN = pygame.color.THECOLORS['lightgreen']

# okno główne
os.environ['SDL_VIDEO_CENTERED'] = '1'    # centrowanie okna
SIZESCREEN = WIDTH, HEIGHT = 1200, 750
screen = pygame.display.set_mode(SIZESCREEN)

# grafika  - wczytywanie znaków
file_names = sorted(os.listdir(r"C:\image"))
for file_name in file_names:
    image_name = file_name[:-4]
    if '_L' in image_name or '_R' in image_name:
        image_name = image_name.upper()
    elif 'L' in image_name:
        image_name = image_name.replace('L', '_L').upper()
    elif 'R' in image_name:
        image_name = image_name.replace('R', '_R').upper()
    else:
       image_name = image_name.upper()
    if 'PLAYER_' in image_name:
        image_name = image_name.replace('PLAYER_', '').upper()
    globals().__setitem__(image_name, pygame.image.load(
        os.path.join(r"C:\image", file_name)))

# grafika postać
IMAGES_R = [WALK_R0, WALK_R1, WALK_R2, WALK_R3, WALK_R4, WALK_R5, WALK_R6, WALK_R7, WALK_R8, WALK_R9]
IMAGES_L = [WALK_L0, WALK_L1, WALK_L2, WALK_L3, WALK_L4, WALK_L5, WALK_L6, WALK_L7, WALK_L8, WALK_L9]

# grafika platformy
GRASS_LIST = [GRASS_S, GRASS_M, GRASS_L, GRASS_F, WATER, BOAT]

TREE_LIST = [TREE_S, TREE_M, TREE_L]

# grafika ściany
WALL_LIST = [WALL, WALL_LEFT, WALL_TOP, WALL_RIGHT, WALL_BOTTOM]
WALL_CORNER_LIST = [WALL_TOP_L, WALL_TOP_R, WALL_BOTTOM_R, WALL_BOTTOM_L]

#wojowniczka
WARRIOR_R = [WARRIOR_R0, WARRIOR_R1, WARRIOR_R2, WARRIOR_R3, WARRIOR_R4, WARRIOR_R5, WARRIOR_R6, WARRIOR_R7, WARRIOR_R8, WARRIOR_R9]
WARRIOR_L = [WARRIOR_L0, WARRIOR_L1, WARRIOR_L2,  WARRIOR_L3, WARRIOR_L4, WARRIOR_L5, WARRIOR_L6, WARRIOR_L7, WARRIOR_L8, WARRIOR_L9]
WARRIOR_DEAD_R = [WARRIOR_DEAD_R0, WARRIOR_DEAD_R1, WARRIOR_DEAD_R2, WARRIOR_DEAD_R3, WARRIOR_DEAD_R4, WARRIOR_DEAD_R5, WARRIOR_DEAD_R6, WARRIOR_DEAD_R7, WARRIOR_DEAD_R8,  WARRIOR_DEAD_R9]
WARRIOR_DEAD_L = [WARRIOR_DEAD_L0, WARRIOR_DEAD_L1, WARRIOR_DEAD_L2, WARRIOR_DEAD_L3, WARRIOR_DEAD_L4, WARRIOR_DEAD_L5, WARRIOR_DEAD_L6, WARRIOR_DEAD_L7, WARRIOR_DEAD_L8,  WARRIOR_DEAD_L9]

#zla_wrozka
FAIRY2_R = [FAIRY2_FLYATTACK_R0,FAIRY2_FLYATTACK_R1, FAIRY2_FLYATTACK_R2, FAIRY2_FLYATTACK_R3, FAIRY2_FLYATTACK_R4, FAIRY2_FLYATTACK_R5, FAIRY2_FLYATTACK_R6, FAIRY2_FLYATTACK_R7, FAIRY2_FLYATTACK_R8, FAIRY2_FLYATTACK_R9]
FAIRY2_L = [FAIRY2_FLYATTACK_L0, FAIRY2_FLYATTACK_L1, FAIRY2_FLYATTACK_L2, FAIRY2_FLYATTACK_L3, FAIRY2_FLYATTACK_L4, FAIRY2_FLYATTACK_L5, FAIRY2_FLYATTACK_L6, FAIRY2_FLYATTACK_L7, FAIRY2_FLYATTACK_L8, FAIRY2_FLYATTACK_L9]
FAIRY2_DEAD_R = [FAIRY2_DIE_R0, FAIRY2_DIE_R1, FAIRY2_DIE_R2, FAIRY2_DIE_R3, FAIRY2_DIE_R4, FAIRY2_DIE_R5, FAIRY2_DIE_R6, FAIRY2_DIE_R7, FAIRY2_DIE_R8, FAIRY2_DIE_R9]
FAIRY2_DEAD_L = [FAIRY2_DIE_L0, FAIRY2_DIE_L1, FAIRY2_DIE_L2, FAIRY2_DIE_L3, FAIRY2_DIE_L4, FAIRY2_DIE_L5, FAIRY2_DIE_L6, FAIRY2_DIE_L7, FAIRY2_DIE_L8, FAIRY2_DIE_L9]

#rycerz
KNIGHT_R = [KNIGHT_WALK_R0, KNIGHT_WALK_R1, KNIGHT_WALK_R2, KNIGHT_WALK_R3, KNIGHT_WALK_R4, KNIGHT_WALK_R5, KNIGHT_WALK_R6, KNIGHT_WALK_R7, KNIGHT_WALK_R8, KNIGHT_WALK_R9]
KNIGHT_L = [KNIGHT_WALK_L0, KNIGHT_WALK_L1, KNIGHT_WALK_L2, KNIGHT_WALK_L3, KNIGHT_WALK_L4, KNIGHT_WALK_L5, KNIGHT_WALK_L6, KNIGHT_WALK_L7, KNIGHT_WALK_L8, KNIGHT_WALK_L9]
KNIGHT_DEAD_R = [KNIGHT_DIE_R0, KNIGHT_DIE_R1, KNIGHT_DIE_R2, KNIGHT_DIE_R3, KNIGHT_DIE_R4, KNIGHT_DIE_R5, KNIGHT_DIE_R6, KNIGHT_DIE_R7, KNIGHT_DIE_R8, KNIGHT_DIE_R9]
KNIGHT_DEAD_L = [KNIGHT_DIE_L0, KNIGHT_DIE_L1, KNIGHT_DIE_L2, KNIGHT_DIE_L3, KNIGHT_DIE_L4, KNIGHT_DIE_L5, KNIGHT_DIE_L6, KNIGHT_DIE_L7, KNIGHT_DIE_L8, KNIGHT_DIE_L9]

#wróżka
FAIRY_L = [FAIRY_L0, FAIRY_L1,FAIRY_L2, FAIRY_L3, FAIRY_L4, FAIRY_L5, FAIRY_L6, FAIRY_L7, FAIRY_L8, FAIRY_L9]
FAIRY_R = [FAIRY_R0, FAIRY_R1,FAIRY_R2, FAIRY_R3, FAIRY_R4, FAIRY_R5, FAIRY_R6, FAIRY_R7, FAIRY_R8, FAIRY_R9]